name: emtrade_tech_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  injectable: ^2.4.2
  go_router: ^14.2.1
  get_it: ^7.7.0
  bloc: ^8.1.4
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  package_info: ^2.0.2
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  image_picker: ^1.1.2
  hive_flutter: ^1.1.0
  flavor: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  another_flushbar: ^1.12.30
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  flutter_jailbreak_detection: ^1.10.0
  pin_code_fields: ^8.0.1
  dotted_border: ^2.1.0
  permission_handler: ^11.3.1
  device_info_plus: ^9.1.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  injectable_generator: ^2.6.1
  build_runner: ^2.4.10
  flutter_gen_runner: ^5.5.0
  json_serializable: ^6.8.0
  envied_generator: ^0.5.4+1
  retrofit_generator: ^8.1.0
  hive_generator: ^2.0.1

flutter:
  # generate icon apps
  generate: true

  uses-material-design: true
  
  # for declaration assets folder
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/fonts/Inter/

  # for setup font on apps
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
